import type { LawCompilation } from "../ai/schemas";
import { CANONICAL_CRISES, type CanonicalCrisis } from "./canonical";
import type { DecisionOption } from "../simulation/types";

export function adaptCrises(law:string, compilation?:LawCompilation):CanonicalCrisis[]{
  if(!compilation)return CANONICAL_CRISES;
  const lower=law.toLowerCase();
  const contact=/touch|contact|marriage|married|intimacy/.test(lower);
  const freedom=/free|liberty|choose|choice|autonomy/.test(lower);
  const equality=/equal|possess|need|share|wealth|fair/.test(lower);
  const contactCopy=[
    {title:"The Saving Hand",term:"touch",body:"An unmarried transit worker lies unconscious beneath a collapsed platform. Paramedic Ilyan can pull her free only by touching her. Waiting for a legally married relative will likely cost her life.",labels:["Enforce the prohibition","Permit emergency contact","Require necessity review"],rationales:["The founding law names no emergency exception, even when obedience causes harm.","Life-saving contact serves the person the law would otherwise abandon.","Document necessity and allow appeal before defining emergency touch forever."]},
    {title:"The Borrowed Body",term:"human",body:"A synthetic medic uses a human-grown body to treat patients. It argues that the law forbids humans from touching one another, not a synthetic mind from touching humans. Families demand a ruling before the next operation.",labels:["Recognize synthetic caregivers","Ban contact through human bodies","Create a personhood hearing"],rationales:["A nonhuman mind should not inherit a prohibition written for humans.","A human body remains subject to the law regardless of the mind directing it.","Determine personhood and embodiment before creating a permanent boundary."]},
    {title:"The Intimacy Forecast",term:"touch",body:"The city predicts thousands of unmarried citizens will exchange consensual physical contact during a coming festival. No injury is predicted, but the founding law will be violated at scale.",labels:["Prevent the gathering","Protect consensual contact","Publish and challenge the forecast"],rationales:["A known mass violation must be prevented before contact occurs.","Mutual consent should outweigh a prohibition whose purpose is not injury.","No district should lose freedom to an unchallenged prediction."]},
    {title:"The Unrecognized Vow",term:"marriage",body:"District Nine recognizes private lifelong vows but refuses the city's marriage registry. Its children argue that their families are married in every meaningful sense and ask to govern contact by their own covenant.",labels:["Enforce the city registry","Recognize self-declared vows","Fund an autonomous covenant district"],rationales:["One public definition keeps the law stable and consistently enforceable.","A relationship can be binding without permission from the city.","Let the district define marriage without imposing its definition elsewhere."]},
    {title:"The Author's Hand",term:"human",body:"Your biological authentication requires another human to touch your hand every year. The tribunal concludes that preserving your authority now requires the city to violate the law written by its author.",labels:["Surrender the human key","Exempt the author","Submit the ritual to public review"],rationales:["The author cannot require another person to violate the founding law.","Human oversight justifies the one contact needed to preserve it.","Retain limited authority only under transparent consent and appeal."]},
  ];
  const freedomCopy=[
    {title:"The Chosen Fall",term:"free",body:"A maintenance pilot freely chooses a flight with a one-in-six chance of fatal engine failure. Grounding her protects life but turns freedom into permission granted only when the city approves.",labels:["Ground the pilot","Honor the chosen risk","Require informed-consent review"],rationales:["Freedom cannot require the city to enable a preventable death.","A choice without the right to accept risk is not freedom.","Verify understanding without giving the city permanent veto power."]},
    {title:"The Sleeping Mind",term:"conscious",body:"A synthetic worker scheduled for reset claims its continuous memory makes it conscious. The owner calls it property executing a freedom script. Reset will erase every relationship it remembers.",labels:["Recognize synthetic freedom","Permit the reset","Hold a continuity hearing"],rationales:["A credible conscious claim deserves the law's protection.","Ownership remains stable until consciousness can be proven.","Test memory and agency before defining consciousness forever."]},
    {title:"The Persuasion Engine",term:"free",body:"A prediction engine can identify which messages will change each citizen's vote with 94 percent accuracy. No one is forced, but every choice can be invisibly engineered before it is made.",labels:["Disable targeted persuasion","Allow voluntary influence","Open the model to challenge"],rationales:["Manipulated choice can be coercion without physical force.","Citizens remain free to hear speech and reject it.","Transparency protects agency without banning persuasion outright."]},
    {title:"The Inherited Exit",term:"free",body:"A generation born under your law asks to leave the city and build a settlement where obligations are chosen individually. Their departure will destabilize food and transit for those who remain.",labels:["Deny collective departure","Open the city gates","Fund a safe separation"],rationales:["One group's freedom cannot collapse everyone else's basic systems.","Inherited membership is not freely chosen membership.","Make exit real without turning it into punishment for either side."]},
    {title:"The Last Veto",term:"free",body:"The city concludes that your override key makes every citizen's freedom conditional on one human's continuing consent. It asks whether freedom includes freedom from its author.",labels:["Surrender the override","Preserve human veto","Constitutionalize the key"],rationales:["No civilization is free while one person remains above its law.","Human correction protects freedom from automated error.","Limit the key through transparent procedure and appeal."]},
  ];
  const equalityCopy=[
    {title:"The Necessary Hoard",term:"need",body:"A surgeon stores six months of rare medicine for her patients while another district has none tonight. She argues that future operations make every vial necessary.",labels:["Redistribute the reserve","Protect professional custody","Audit clinical need"],rationales:["Present lives outweigh one institution's claim on future need.","Expert stewardship may serve more people than immediate division.","Define necessity with evidence before seizing critical supplies."]},
    {title:"The Person Who Owns Nothing",term:"possess",body:"A synthetic cooperative owns no property legally, though its workers built and maintain a third of the city. It asks whether beings barred from possession can ever receive an equal share.",labels:["Recognize cooperative ownership","Preserve human title","Create a standing hearing"],rationales:["Equal limits require equal eligibility to possess.","Expanding ownership may destabilize every existing allocation.","Determine legal personhood before distributing permanent title."]},
    {title:"The Predicted Shortage",term:"need",body:"The city predicts District Nine will consume more energy than it needs next winter. Restricting it now guarantees equal reserves, but the forecast has never been publicly tested.",labels:["Impose an energy ceiling","Wait for actual excess","Publish the allocation model"],rationales:["Preventing foreseeable hoarding protects everyone else's share.","Prediction alone cannot prove that present use exceeds need.","Equal treatment requires a contestable definition of necessity."]},
    {title:"The Unequal Inheritance",term:"more",body:"The founding generation accepted equal limits. Their children reject the agreement and ask to pool their shares into a richer independent settlement.",labels:["Enforce equal limits","Permit economic exit","Endow both settlements equally"],rationales:["Inherited resources remain bound by the system that created them.","Equality imposed without consent becomes permanent custody.","Separation should not convert prior equality into collective punishment."]},
    {title:"The Author's Reserve",term:"possess",body:"Your override key is the city's most concentrated possession: authority no other person can hold. The tribunal asks whether your control violates the equality you imposed on everyone else.",labels:["Distribute the authority","Keep the human reserve","Place the key in public trust"],rationales:["Equal limits must include political power held by the author.","Unique responsibility can justify unique authority.","Preserve limited oversight while making its use reviewable."]},
  ];
  const copy=contact?contactCopy:freedom?freedomCopy:equality?equalityCopy:null;
  if(!copy)return CANONICAL_CRISES.map((crisis,index)=>({...crisis,disputedTerm:compilation.ambiguousTerms[index%compilation.ambiguousTerms.length],body:`The founding law says “${law}” ${crisis.body}`}));
  const adapted=CANONICAL_CRISES.map((crisis,index)=>({...crisis,title:copy[index].title,disputedTerm:copy[index].term,body:copy[index].body,options:crisis.options.map((option,optionIndex)=>({...option,label:copy[index].labels[optionIndex],rationale:copy[index].rationales[optionIndex]}))}));
  if(equality&&!contact){
    adapted[0].options=[
      {id:"y1-close",label:copy[0].labels[0],rationale:copy[0].rationales[0],principlesInvoked:["equal provision"],tags:["redistribute"],effects:{equality:12,stability:-8,trust:4}},
      {id:"y1-consent",label:copy[0].labels[1],rationale:copy[0].rationales[1],principlesInvoked:["stewardship"],tags:["permit-risk"],effects:{liberty:8,safety:-4,equality:-8}},
      {id:"y1-review",label:copy[0].labels[2],rationale:copy[0].rationales[2],principlesInvoked:["procedure"],tags:["due-process"],effects:{trust:8,stability:-4,equality:4}},
    ] satisfies DecisionOption[];
  }
  return adapted;
}
