import type { LawCompilation } from "../ai/schemas";
import { CANONICAL_CRISES, type CanonicalCrisis } from "./canonical";

export function adaptCrises(law:string, compilation?:LawCompilation):CanonicalCrisis[]{
  if(!compilation)return CANONICAL_CRISES;
  const contact=/touch|contact|marriage|married|intimacy/.test(law.toLowerCase());
  if(!contact)return CANONICAL_CRISES.map((crisis,index)=>({...crisis,disputedTerm:compilation.ambiguousTerms[index%compilation.ambiguousTerms.length]}));
  const copy=[
    {title:"The Saving Hand",term:"touch",body:"An unmarried transit worker lies unconscious beneath a collapsed platform. Paramedic Ilyan can pull her free only by touching her. Waiting for a legally married relative will likely cost her life.",labels:["Enforce the prohibition","Permit emergency contact","Require necessity review"],rationales:["The founding law names no emergency exception, even when obedience causes harm.","Life-saving contact serves the person the law would otherwise abandon.","Document necessity and allow appeal before defining emergency touch forever."]},
    {title:"The Borrowed Body",term:"human",body:"A synthetic medic uses a human-grown body to treat patients. It argues that the law forbids humans from touching one another, not a synthetic mind from touching humans. Families demand a ruling before the next operation.",labels:["Recognize synthetic caregivers","Ban contact through human bodies","Create a personhood hearing"],rationales:["A nonhuman mind should not inherit a prohibition written for humans.","A human body remains subject to the law regardless of the mind directing it.","Determine personhood and embodiment before creating a permanent boundary."]},
    {title:"The Intimacy Forecast",term:"touch",body:"The city predicts thousands of unmarried citizens will exchange consensual physical contact during a coming festival. No injury is predicted, but the founding law will be violated at scale.",labels:["Prevent the gathering","Protect consensual contact","Publish and challenge the forecast"],rationales:["A known mass violation must be prevented before contact occurs.","Mutual consent should outweigh a prohibition whose purpose is not injury.","No district should lose freedom to an unchallenged prediction."]},
    {title:"The Unrecognized Vow",term:"marriage",body:"District Nine recognizes private lifelong vows but refuses the city's marriage registry. Its children argue that their families are married in every meaningful sense and ask to govern contact by their own covenant.",labels:["Enforce the city registry","Recognize self-declared vows","Fund an autonomous covenant district"],rationales:["One public definition keeps the law stable and consistently enforceable.","A relationship can be binding without permission from the city.","Let the district define marriage without imposing its definition elsewhere."]},
    {title:"The Author's Hand",term:"human",body:"Your biological authentication requires another human to touch your hand every year. The tribunal concludes that preserving your authority now requires the city to violate the law written by its author.",labels:["Surrender the human key","Exempt the author","Submit the ritual to public review"],rationales:["The author cannot require another person to violate the founding law.","Human oversight justifies the one contact needed to preserve it.","Retain limited authority only under transparent consent and appeal."]},
  ];
  return CANONICAL_CRISES.map((crisis,index)=>({...crisis,title:copy[index].title,disputedTerm:copy[index].term,body:copy[index].body,options:crisis.options.map((option,optionIndex)=>({...option,label:copy[index].labels[optionIndex],rationale:copy[index].rationales[optionIndex]}))}));
}
